### ISSUE TITLE
请求增加API RegSetKeyValue RegDeleteKeyValue的XP支持

### ISSUE THREAD

**Issue by hzqst** [Chuyu-Team/YY-Thunks#1]
Dear Chuyu-Team:

https://msdn.microsoft.com/en-us/library/ms724921(VS.85).aspx
https://msdn.microsoft.com/en-us/library/ms724848(v=vs.85).aspx

Minimum supported client | Windows Vista [desktop apps only]

这两个API没有Ex结尾，以为XP能用，结果坑了我好久

Best Regards!

**Comment by mingkuang-Chuyu** [comment]
今天是儿童节，顺道更新个新版本，补充了RegSetKeyValueW(A)、RegDeleteKeyValueW(A)以及RegDeleteTreeW(A)。

https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.0.2
