### ISSUE TITLE
.NET Native AOT项目 是不是得UWP或者WinRT 的项目?

### ISSUE THREAD

**Issue by sgf** [Chuyu-Team/YY-Thunks#105]
文档中所说的 [2.1.2. .NET Native AOT项目](https://github.com/Chuyu-Team/YY-Thunks/blob/master/Readme.osc.md#212-net-native-aot%E9%A1%B9%E7%9B%AE) 是不是得必须是 UWP或者WinRT 的项目?

我用普通的 .net8-windows 项目安装了 YY-Thunks nuget 包,
发现 AOT发布后并无什么明显的变化.
我主要是查看了exe的文件体积.

我是只在主项目(Exe)上安装了 YY-Thunks

**Comment by mingkuang-Chuyu** [comment]
不要求UWP之类的。不过你的根据文件大小就反馈，你确定没有在逗我……？

如果有问题请直接描述问题，当前我暂时只能设置为无效问题。

另外最好每个项目都安装yY-Thunks，我并不清楚你是不是只需要主程序在低版本系统里跑。

**Comment by sgf** [comment]
> 不要求UWP之类的。不过你的根据文件大小就反馈，你确定没有在逗我……？
> 
> 如果有问题请直接描述问题，当前我暂时只能设置为无效问题。
> 
> 另外最好每个项目都安装yY-Thunks，我并不清楚你是不是只需要主程序在低版本系统里跑。

好的,谢谢,我直接安装了VC-LTL 体积大小终于有反应了,嘿嘿.
暂时先关掉,我现在没有xp或win7测试环境,后面有问题的话 我再反馈.

**Comment by mingkuang-Chuyu** [comment]
你好，或许可以使用 YY-Thunks自带的YY.Depends.Analyzer分析应用程序。虽然不能发生所有的兼容性问题。


使用方法：
// 检测你的编译产物是否引用了Windows XP不支持的接口
YY.Depends.Analyzer  "你的编译产物路径" /IgnoreReady

// 检测你的编译产物是否引用了Windows 7 RTM不支持的接口
YY.Depends.Analyzer  "你的编译产物路径" /IgnoreReady /Target:6.1.7600

________________________________
发件人: Soar ***@***.***>
发送时间: 2024年6月29日 19:19
收件人: Chuyu-Team/YY-Thunks ***@***.***>
抄送: mingkuang ***@***.***>; Comment ***@***.***>
主题: Re: [Chuyu-Team/YY-Thunks] .NET Native AOT项目 是不是得UWP或者WinRT 的项目? (Issue #105)


不要求UWP之类的。不过你的根据文件大小就反馈，你确定没有在逗我……？

如果有问题请直接描述问题，当前我暂时只能设置为无效问题。

另外最好每个项目都安装yY-Thunks，我并不清楚你是不是只需要主程序在低版本系统里跑。

好的,谢谢,我直接安装了VC-LTL 体积大小终于有反应了,嘿嘿.
暂时先关掉,我现在没有xp或win7测试环境,后面有问题的话 我再反馈.

―

**Comment by sgf** [comment]
好的,非常感谢.我还只是在做测试. 开发程序之前做的实验性测试,后面我会深入使用的.
