### ISSUE TITLE
NtReleaseKeyedEvent NtWaitForKeyedEvent 不支持Win2K, 应该如何实现？

### ISSUE THREAD

**Issue by lygstate** [Chuyu-Team/YY-Thunks#106]

**Comment by mingkuang-Chuyu** [comment]
不知道，暂时也不会对Windows 2000投入过多精力。如果你有方案可以提供PR。

> Windows 2000兼容是为了360安全卫士某些项目服务的，如果需求方没有提出更多需求，我不会投入更多精力。
