### ISSUE TITLE
Vistual Studio 2010 SP1编译一个DLL时找不到找不到threadSafeInit、sizedDealloc相关符号

### ISSUE THREAD

**Issue by sinfee** [Chuyu-Team/YY-Thunks#107]
你好，我编译的项目是一个MFC 规则 DLL ,MD方式， 编译环境是 vc2010+sp1 英文版本，在链接时提示下面的错误：
release x64平台：
1>YY_Thunks_for_WinXP.obj : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *,unsigned __int64)" (??3@YAXPEAX_K@Z)
1>YY_Thunks_for_WinXP.obj : error LNK2001: unresolved external symbol _Init_thread_header
1>YY_Thunks_for_WinXP.obj : error LNK2001: unresolved external symbol _Init_thread_footer
1>YY_Thunks_for_WinXP.obj : error LNK2001: unresolved external symbol _Init_thread_epoch

relase win32平台：
1>YY_Thunks_for_WinXP.obj : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *,unsigned int)" (??3@YAXPAXI@Z)
1>YY_Thunks_for_WinXP.obj : error LNK2001: unresolved external symbol __Init_thread_header
1>YY_Thunks_for_WinXP.obj : error LNK2001: unresolved external symbol __Init_thread_footer
1>YY_Thunks_for_WinXP.obj : error LNK2001: unresolved external symbol __Init_thread_epoch

debug x64 平台：
1>YY_Thunks_for_WinXP.obj : error LNK2019: unresolved external symbol "void __cdecl operator delete(void *,unsigned __int64)" (??3@YAXPEAX_K@Z) referenced in function "public: virtual void * __cdecl YY::Thunks::`anonymous namespace'::BCryptAlgorithmByCryptoAPI<struct YY::Thunks::`anonymous namespace'::BCrypt3DESAlgorithm>::`scalar deleting destructor'(unsigned int)" (??_G?$BCryptAlgorithmByCryptoAPI@UBCrypt3DESAlgorithm@?A0xde699b42@Thunks@YY@@@?A0xde699b42@Thunks@YY@@UEAAPEAXI@Z)
1>YY_Thunks_for_WinXP.obj : error LNK2019: unresolved external symbol _Init_thread_header referenced in function SetThreadpoolThreadMaximum
1>YY_Thunks_for_WinXP.obj : error LNK2019: unresolved external symbol _Init_thread_footer referenced in function SetThreadpoolThreadMaximum
1>YY_Thunks_for_WinXP.obj : error LNK2001: unresolved external symbol _Init_thread_epoch

debug win32平台：
1>YY_Thunks_for_WinXP.obj : error LNK2019: unresolved external symbol "void __cdecl operator delete(void *,unsigned int)" (??3@YAXPAXI@Z) referenced in function "public: virtual void * __thiscall YY::Thunks::`anonymous namespace'::BCryptAlgorithmByCryptoAPI<struct YY::Thunks::`anonymous namespace'::BCrypt3DESAlgorithm>::`scalar deleting destructor'(unsigned int)" (??_G?$BCryptAlgorithmByCryptoAPI@UBCrypt3DESAlgorithm@?A0xde699b42@Thunks@YY@@@?A0xde699b42@Thunks@YY@@UAEPAXI@Z)
1>YY_Thunks_for_WinXP.obj : error LNK2019: unresolved external symbol __Init_thread_header referenced in function "public: static class YY::Thunks::Fallback::A0xde699b42::TP_Pool * __fastcall YY::Thunks::Fallback::`anonymous namespace'::TP_Pool::GetDefaultPool(void)" (?GetDefaultPool@TP_Pool@?A0xde699b42@Fallback@Thunks@YY@@SIPAV12345@XZ)
1>YY_Thunks_for_WinXP.obj : error LNK2019: unresolved external symbol __Init_thread_footer referenced in function "public: static class YY::Thunks::Fallback::A0xde699b42::TP_Pool * __fastcall YY::Thunks::Fallback::`anonymous namespace'::TP_Pool::GetDefaultPool(void)" (?GetDefaultPool@TP_Pool@?A0xde699b42@Fallback@Thunks@YY@@SIPAV12345@XZ)
1>YY_Thunks_for_WinXP.obj : error LNK2001: unresolved external symbol __Init_thread_epoch

**Comment by mingkuang-Chuyu** [comment]
@sinfee 请查收 https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.1.2-Beta5

**Comment by sinfee** [comment]
@mingkuang-Chuyu 感谢，已经成功编译
