### ISSUE TITLE
Windows XP 上卸载 DLL 时，在 FreeTlsIndex 中发生死循环

### ISSUE THREAD

**Issue by gexgd0419** [Chuyu-Team/YY-Thunks#108]
https://github.com/Chuyu-Team/YY-Thunks/blob/468262997dd81db3233b879482cd2ff1b8a96604/src/Thunks/DllMainCRTStartup.hpp#L336-L346

卸载 DLL 时，由于某个节点的 `pNext` 指向节点自身，该循环永远不会结束。

![image](https://github.com/user-attachments/assets/bfa4baeb-5cfd-4606-a2e9-813bf8dddae8)

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.1.2-Beta7

**Comment by mingkuang-Chuyu** [comment]
感谢反馈
