### ISSUE TITLE
lack of some function in "dxgi.dll" and  "shcore.dll"

### ISSUE THREAD

**Issue by BH2WFR** [Chuyu-Team/YY-Thunks#111]
library: **static linked Qt 6.5.3**

1. "`GetProcessDpiAwareness`" in "shcore.dll"  before Windows 8.1 (used by Qt6 static links)
(https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getprocessdpiawareness)

2. "`CreateDXGIFactory2`" in "dxgi.dll" before Windows 8.1 (used by Qt6 static links)
(https://learn.microsoft.com/en-us/windows/win32/api/dxgi1_3/nf-dxgi1_3-createdxgifactory2)

3. "`InitializeTouchInjection`" and "`InjectTouchInput`" in user32.dll before Windows 8 
(https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-initializetouchinjection)
(https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-injecttouchinput)

4. `GetCurrentPackageFullName` in kernel32.dll  (used by Qt6 static links)
https://learn.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-getcurrentpackagefullname

6. some functions in user32.dll (used by Qt6 static links)
  - `AreDpiAwarenessContextsEqual`
  - `EnableNonClientDpiScaling``
  - `GetAwarenessFromDpiAwarenessContext`
  - `GetPointerDeviceRects`
  - `GetPointerFrameTouchInfo`
  - `GetPointerFrameTouchInfoHistory`
  - `GetPointerInfo``
  - `GetPointerPenInfoHistory`
  - `GetThreadDpiAwarenessContext`
  - `GetWindowDpiAwarenessContext`
  - `SetDisplayAutoRotationPreferences`
  - `SkipPointerFrameMessages`

I'm trying to add them for a PR, but It seems hard. Any suggestions for how to add them?

I tried to add `GetProcessDpiAwareness` function in `src/Thunks/shcore.hpp`, but It failed to compile.

# Report By YY.Depends.Analyzer (Target:6.0.6000-x64)
## api-ms-win-shcore-scaling-l1-1-1.dll
| API                                        | YY-Thunks Ready | Supported OS | Ref Module|
| ----                                       | --------------  | ------------ | --------|
| GetProcessDpiAwareness | No | 6.3.9600 ||

## dxgi.dll
| API                                        | YY-Thunks Ready | Supported OS | Ref Module|
| ----                                       | --------------  | ------------ | --------|
| CreateDXGIFactory2 | No | 6.3.9600 ||

## KERNEL32.dll
| API                                        | YY-Thunks Ready | Supported OS | Ref Module|
| ----                                       | --------------  | ------------ | --------|
| GetCurrentPackageFullName | No | 6.2.9200<br>6.3.9600 ||

## USER32.dll
| API                                        | YY-Thunks Ready | Supported OS | Ref Module|
| ----                                       | --------------  | ------------ | --------|
| AreDpiAwarenessContextsEqual | No |  ||
| EnableNonClientDpiScaling | No |  ||
| GetAwarenessFromDpiAwarenessContext | No |  ||
| GetPointerDeviceRects | No | 6.2.9200<br>6.3.9600 ||
| GetPointerFrameTouchInfo | No | 6.2.9200<br>6.3.9600 ||
| GetPointerFrameTouchInfoHistory | No | 6.2.9200<br>6.3.9600 ||
| GetPointerInfo | No | 6.2.9200<br>6.3.9600 ||
| GetPointerPenInfoHistory | No | 6.2.9200<br>6.3.9600 ||
| GetThreadDpiAwarenessContext | No |  |            |
| GetWindowDpiAwarenessContext | No |  |            |
| SetDisplayAutoRotationPreferences | No | 6.2.9200<br>6.3.9600 ||
| SkipPointerFrameMessages | No | 6.2.9200<br>6.3.9600 ||

**Comment by mingkuang-Chuyu** [comment]
感谢你的支持，其实YY-thunks压缩包已经提供`YY.Depends.Analyzer`独立工具，可以快速分析缺失的依赖
```
; 比如分析Google浏览器 XP系统上缺失的API，帮助大家快速查找缺失API
YY.Depends.Analyzer  "C:\Program Files\Google\Chrome\Application\125.0.6422.113" /IgnoreReady
```

**Comment by mingkuang-Chuyu** [comment]
统一在QT API缺失中修复
