### ISSUE TITLE
.net AOT windows server 2008 R2 SP1 运行后没有任何反应。

### ISSUE THREAD

**Issue by sgf** [Chuyu-Team/YY-Thunks#112]
本身是  .net8.0 命令行应用程序   x64 AOT发布
~我安装了 VC-LTL 最新版本预览版~
包括YY-Thunk最新版本预览版

~改成.net 8.0-windows~ 是否使用 net8.0-windows 也并无区别
~使用了 <SupportedOSPlatformVersion>5.1</SupportedOSPlatformVersion> 选项~ 是否使用5.1支持并无区别

windows server 2019 上运行正常

但是 windows server 2008 R2 SP1 上面 运行后没有任何反应，哪怕一个字的错误消息都没有。

![image](https://github.com/user-attachments/assets/24314ddb-26ca-4e81-ba95-9c494a173134)

发布过程中没有见到有价值的日志。
![image](https://github.com/user-attachments/assets/516d649f-a369-436e-b6e5-99f19500ab5e)

windows 系统日志里面也没有什么有价值的日志

为此我准备了最小复现demo的代码仓库（就是最基本的helloworld即可复现）：
https://github.com/sgf/YYThunksOnSvr2008Issue

**Comment by mingkuang-Chuyu** [comment]
Windows 7 RTM x64(6.1.7600) 无法重现。
> TargetFramework = net8.0-windows

![image](https://github.com/user-attachments/assets/2f26b02d-3f39-4798-9c61-dcabde03eb01)

![image](https://github.com/user-attachments/assets/ecba2a5d-0aaa-4d82-b0e1-5c6aff44dd88)

**Comment by sgf** [comment]
> Windows 7 RTM x64(6.1.7600) 无法重现。

没说是Win7啊，说的是Server2008 R2 X64 阿里云的服务器。

**Comment by mingkuang-Chuyu** [comment]
Server 2008 R2跟win7内核相同啊。
而且我是RTM，内核版本其实比你更低。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sgf** [comment]
> Server 2008 R2跟win7内核相同啊。 而且我是RTM，内核版本其实比你更低。 

内核相同,不代表系统就兼容啊.

我已经把服务器远程 登录的账号密码发给你.你有空的话,把AOT的程序放上去测试看看吧.
有个文件夹打开着,里面也有我之前复制过去测试用的一个exe

**Comment by mingkuang-Chuyu** [comment]
这种系统的差异带来兼容性问题的概率极低。

我认为现在自查是不是操作原因。

另外程序运行没有反应，也是可以调试一下看看。毕竟你是开发不是QA更不是普通用户，只关注程序有没有正常启动，而不调试介入本身也是不合理的事情。


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sgf** [comment]
>  另外程序运行没有反应，也是可以调试一下看看。毕竟你是开发不是QA更不是普通用户，只关注程序有没有正常启动，而不调试介入本身也是不合理的事情。 

怎么说呢.如果是本地的话,或许就很方便了.但现在是服务器环境.虽然我也有服务器环境的调试方法.但问题是至少需要软件可以启动,我才能够附加调试.

目前的这种情况的话,应该是无法进入到任何我程序逻辑的范畴,因此可能只能用一些特殊的方法进行调试.比如在服务器安装windbg.
但我不擅长使用windbg之类的工具,否则我就去搞c/c++ 了.(不擅长=说难听点就是不会用)

如果您需要,安装任何软件或者工具的话,尽管安装. 另外,时间这块我倒也并不急.

**Comment by mingkuang-Chuyu** [comment]
并非YY-Thunks问题，.NET申请内存失败发生OOM异常退出。手工添加2G页面文件后问题解决。

最初机器只有1GB物理内存、又没有页面文件。然后机器整体只有100MB空闲的commit页面可用，看起来.NET AOT程序对内存要求比较高，虽然是个Hello word，但是开销至少在100MB以上……

![P%4SD FYYT((IBFY1AA3~TK](https://github.com/user-attachments/assets/3e55f257-bc26-4eb2-904e-10d90d802e29)

**Comment by sgf** [comment]
大佬牛逼
