### ISSUE TITLE
在XP下将链接到YY-Thunks的MSVCR14XD.dll注入到一个WPF(.NET 3.5)进程会报错

### ISSUE THREAD

**Issue by sonyps5201314** [Chuyu-Team/YY-Thunks#114]
## 影响范围
* NT 5.1 或者更低版本
* 使用10.0.26100.0 UCRT，并且没有使用VC-LTL

## 原因
线程退出时，Tls回调调用ThreadDetachCallback 已经释放了Fls的模拟层 s_pFlsDataBlock。
随后DllMain的DLL_THREAD_DETACH中CRT尝试释放PTD，而PTD是基于Fls实现的，但是Fls模拟层已经被释放，再次释放导致二次释放。

该问题目前只影响10.0.26100.0 UCRT，因为该版本开始，PTD强制使用Fls，恰好触发了YY-Thunks的设计缺陷。

## 解决版本
* [v1.1.3-Beta2](https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.1.3-Beta2)

![P8Y6Z__L)76970OPZ$6()KT](https://github.com/user-attachments/assets/44957504-2421-4b13-a8c8-a98d7a97a221)

![OBBU`T WIH0JQM3O4AYYUKB](https://github.com/user-attachments/assets/ab99617a-18f0-4c14-bc69-4e7757038b52)

dmp链接（有效期仅一天）：
https://f.ws28.cn/f/f07vsb8ahx4

**Comment by mingkuang-Chuyu** [comment]
原因：
线程退出时，Tls回调调用ThreadDetachCallback 已经释放了Fls的模拟层 s_pFlsDataBlock。
随后DllMain的DLL_THREAD_DETACH中CRT尝试释放PTD，而PTD是基于Fls实现的，但是Fls模拟层已经被释放，最终释放PTD时也指针。
