### ISSUE TITLE
v141 + Win32 链接时报告找不到__ftoul2_legacy

### ISSUE THREAD

**Issue by sinfee** [Chuyu-Team/YY-Thunks#115]
1.1.3 beta3 版本编译测试时，出现下面的错误：

YY_Thunks_for_WinXP.obj : error LNK2019: 无法解析的外部符号 __ftoul2_legacy，该符号在函数 "int __cdecl YY::Thunks::internal::`anonymous namespace'::CompareFastValue(struct YY::Thunks::internal::A0xca5b566b::FastValue const &,struct YY::Thunks::internal::A0xca5b566b::FastValue const &)" (?CompareFastValue@?A0xca5b566b@internal@Thunks@YY@@YAHABUFastValue@1234@0@Z) 中被引用

更低的版本没有测试

**Comment by mingkuang-Chuyu** [comment]
这个跟8.1 SDK无关，只跟CRT有关。话说在cpp里添加下面这句话应该就问题了吧？

```cpp
#if defined(_M_IX86)
// 直接转发一下，因为UCRT开始，微软将`__ftol2` 改名为 `__ftoul2_legacy`
#pragma comment(linker, "/alternatename:__ftoul2_legacy=__ftol2")
#endif
```

**Comment by sinfee** [comment]
感谢！前面版本没有出这个错误，我是使用了visual studio 2022 17.10 环境，v141+SDK8.1 编译时提示的错误，改成10.0以上的sdk就没有错误了。

**Comment by sinfee** [comment]
![image](https://github.com/user-attachments/assets/cacaa1fd-7c42-48a2-9a55-5056434280aa)

**Comment by mingkuang-Chuyu** [comment]
@sinfee 是的，已经确认了，`__ftoul2_legacy` 是 VS2022新增函数。所以只要你不用 v143 就会又问题。

x64因为是直接内联SSE2，所以也没问题
