### ISSUE TITLE
XP不支持SetFileInformationByHandle传入FileRenameInfo

### ISSUE THREAD

**Issue by zeroclear** [Chuyu-Team/YY-Thunks#12]
GetFileInformationByHandleEx(FileRemoteProtocolInfo)最终转换成NtQueryInformationFile(FileRemoteProtocolInformation)，但XP只支持编号小于41的功能，导致返回FALSE，错误号为ERROR_INVALID_PARAMETER（STATUS_INVALID_INFO_CLASS）
https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-file_remote_protocol_info
MSDN上也说了这个功能最低要Win7，建议在文档或注释里做一下说明

**Comment by zeroclear** [comment]
SetFileInformationByHandle里用到了RtlDosPathNameToNtPathName_U_WithStatus，但XP里没有这个函数，try_get_RtlDosPathNameToNtPathName_U_WithStatus返回nullptr，直接失败。我的方案是用RtlDosPathNameToNtPathName_U代替

**Comment by mingkuang-Chuyu** [comment]
感谢，SetFileInformationByHandle问题我需要更进

**Comment by mingkuang-Chuyu** [comment]
根据反馈者的意见，XP不存在 RtlDosPathNameToNtPathName_U_WithStatus。改用RtlDosPathNameToNtPathName_U实现。

**Comment by mingkuang-Chuyu** [comment]
v1.0.3-Beta4
