### ISSUE TITLE
使用GetProcAddress的方式调用接口将不起作用

### ISSUE THREAD

**Issue by zgliubo** [Chuyu-Team/YY-Thunks#128]
```cpp
GetProcAddress(
    GetModuleHandle(TEXT("kernel32.dll")),
    "WerRegisterRuntimeExceptionModule");
```
上述代码在xp上始终返回NULL

**Comment by mingkuang-Chuyu** [comment]
是的，行为符合预期。设计上，如果主动显试加载，那么就认为自己兼容判断，自己处理。

请问现在有什么问题吗？

**Comment by zgliubo** [comment]
谢谢, 但是有些开源库它会自己兼容判断然后跑异常, 是否能拦截GetProcAddress, 如果返回只是空就给他补上?

**Comment by mingkuang-Chuyu** [comment]
@zgliubo 很抱歉，暂时不能。

因为GetProcAddress拦截代价是惊人的，将导致链接器无法剔除那些不使用的函数。

GetProcAddress时已经处于运行时获取，如果需要返回WerRegisterRuntimeExceptionModule地址，那么这势必yY-Thunks始终带上WerRegisterRuntimeExceptionModule的实现，便于GetProcAddress使用。这会让所有使用yY-Thunks的二进制产物都变大。

我目前有下面几种处理方案：
1. 修改对应的源代码，不要目标代码发生异常。
2. 自己修改一下yY-Thunks的GetProcAddress，特意让它返回一个WerRegisterRuntimeExceptionModule。

当然如果你有更好，更通用的解决方案也可以跟我沟通。

**Comment by zgliubo** [comment]
好的, 谢谢您的解答
