### ISSUE TITLE
在启用 /guard:ehcont 情况下 Debug 编译有概率在抛 C++ 异常时闪退的情况

### ISSUE THREAD

**Issue by MouriNaruto** [Chuyu-Team/YY-Thunks#131]
相关问题刚刚和老鸭子私信讨论，原本我猜测是 VC-LTL 的问题，但实测是 YY-Thunks 导致的原因。

有问题的二进制和 dump 已经通过 QQ 私聊发送给老鸭子。

毛利

**Comment by MiroKaku** [comment]
附加一个编译警告：

```
1>YY_Thunks_for_Vista.obj : warning LNK4291: 模块可能包含 "__except" (结构化异常处理)，但未使用 /guard:ehcont 进行编译；正在生成必需的元数据
```

版本：
[Mile.Project.Configurations](https://github.com/ProjectMile/Mile.Project.Configurations) 内置的 1.1.2 版本

**Comment by mingkuang-Chuyu** [comment]
已经确认微软的UCRT是开启的`/guard:ehcont` 构建的。本地也进行了验证。开启`/guard:ehcont` 后任然兼容老版本的工具链。

YY-Thunks也只能跟随开启，避免异常无法正常派发。
