### ISSUE TITLE
Request implement of SHCreateItemFromParsingName 

### ISSUE THREAD

**Issue by lygstate** [Chuyu-Team/YY-Thunks#20]

**Comment by mingkuang-Chuyu** [comment]
If possible, please try to provide the code.

**Comment by mingkuang-Chuyu** [comment]
可以打开此问题，如果有其他用户需要有什么意见可以在这里回复。

如果你有能力请主动提交实现。

如果你没有这样的能力那么请说明支持这个函数的理由？有什么实际的使用场景？

我不接受仅仅的为了添加而添加他们，必须要有实际的使用场景作为支撑。

**Comment by qiudaowen** [comment]
使用过程当中 RtlpWakeByAddress 会有卡死的情况：
![image](https://user-images.githubusercontent.com/23030025/135411623-0ff30a45-bca2-4536-aadc-1e58733fbd40.png)
这个感觉应该放到 for 循环内

**Comment by mingkuang-Chuyu** [comment]
@qiudaowen 如果有问题应该开  issues

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.5-Beta3
