### ISSUE TITLE
Software Support and Windows 7

### ISSUE THREAD

**Issue by c-sanchez** [Chuyu-Team/YY-Thunks#22]
Hi, I make this topic more to make some questions,
I would like know what software have been test which works now with YY-Thunks in Windows XP, could be nice have some list with details and maybe screenshots even.

And.. I wonder also if possible even used with Windows 7, since now some software like Adobe Photosho 2021 (v22) and more recent 2020 (v21) have dropped Windows 7 support, where is not even possible to install.
Othe software without  Windows 7 support now is VMware 16.x, this was solved thanks to archeYR (has a YouTube channel), but it might be nice to actually solve this too with something like YY-Thunks as well..

https://youtu.be/j7AaMKg607Q

**Comment by MouriNaruto** [comment]
YY-Thunks is a static library solution for software developer to adapt their software to old windows versions.

**Comment by mingkuang-Chuyu** [comment]
Of course, you can do this.

**Comment by mingkuang-Chuyu** [comment]
Note that this library is for developers. If developers use this library when compiling their programs, it will automatically solve some XP compatibility problemes.

**Comment by zeroclear** [comment]
> Oh well, I had to lower the version check to Windows 6.1, and change the user32 import into a custom DLL which forwards all Win7 calls to a native user32, but also has stubs for two missing Windows 8+ functions. All of that in single vmware-vmx.exe file. I also had to modify the installers so that they (more or less) install on Windows 7. So yeah, not really that much, I would say that it was almost artificially blocked on Windows 7...

I have watched the page, and above is his description. In fact, Win7 has full functionality to support this software, except two useless APIs RegisterSuspendResumeNotification and UnregisterSuspendResumeNotification. And Win8+ just has different layout for dlls. So hack binary file will effect, including remove version check, ignore lack APIs, and arrange dll's reference.
To natively support Win7, developers should use YY-thunks in their source code, and YY-thunks must implement all system functions they using. Finally they can build a Win7 version, which don't need hack.

**Comment by mingkuang-Chuyu** [comment]
关闭
