### ISSUE TITLE
尝试消除Chrome 116项目中Windows XP、Windows 7不支持的接口

### ISSUE THREAD

**Issue by mingkuang-Chuyu** [Chuyu-Team/YY-Thunks#29]
截至2023年7月8日，此列表更新为Chrome 116内核API缺失的情况。打勾则表明已经支持。

目前，此任务的优先级比较低，某些API完整的支持投入人力也比较惊人，也欢迎大家提供PR。

## API行为修复
* [x] FindFirstFileEx
   - 针对XP、Vista添加FIND_FIRST_EX_LARGE_FETCH、FindExInfoBasic参数兼容

### KERNEL32.DLL
* [x] DiscardVirtualMemory
* [x] GetProcessMitigationPolicy
* [x] PrefetchVirtualMemory
* [x] SetDefaultDllDirectories
* [x] SetProcessInformation
* [x] SetProcessMitigationPolicy
* [x] SetThreadInformation
* [x] GetFirmwareType
* [x] GetThreadInformation

### USERENV.DLL
* [x] CreateAppContainerProfile
* [x] DeriveAppContainerSidFromAppContainerName
* [x] GetAppContainerFolderPath
* [x] GetAppContainerRegistryLocation
### ADVAPI32.DLL
* [x] EventSetInformation
### MFPLAT.DLL
* [x] MFCreateDXGIDeviceManager
* [x] MFCreateDXGISurfaceBuffer
* [x] MFLockDXGIDeviceManager
* [x] MFUnlockDXGIDeviceManager
### POWRPROF.DLL
* [x] PowerDeterminePlatformRoleEx
### BLUETOOTHAPIS.DLL
* [x] BluetoothGATTGetCharacteristicValue
* [x] BluetoothGATTGetCharacteristics
* [x] BluetoothGATTGetDescriptors
* [x] BluetoothGATTGetServices
* [x] BluetoothGATTRegisterEvent
* [x] BluetoothGATTSetCharacteristicValue
* [x] BluetoothGATTSetDescriptorValue
* [x] BluetoothGATTUnregisterEvent
### API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
* [x] RoOriginateError
### User32.dll
* [x] RegisterSuspendResumeNotification
### NETAPI32.DLL
* [x] NetFreeAadJoinInformation
* [x] NetGetAadJoinInformation
### WinHttp.dll
* [x] WinHttpCreateProxyResolver
* [x] WinHttpFreeProxyResult
* [x] WinHttpGetProxyForUrlEx
* [x] WinHttpGetProxyResult

## Windows XP缺失
* [x] AcquireSRWLockExclusive
* [x] AcquireSRWLockShared
* [x] InitializeSRWLock
* [x] ReleaseSRWLockExclusive
* [x] ReleaseSRWLockShared
* [x] TryAcquireSRWLockExclusive
* [x] InitializeConditionVariable
* [x] SleepConditionVariableCS
* [x] SleepConditionVariableSRW
* [x] WakeAllConditionVariable
* [x] WakeConditionVariable
* [x] InitOnceBeginInitialize
* [x] InitOnceComplete
* [x] InitOnceExecuteOnce
* [x] InitializeCriticalSectionEx
* [x] CancelIoEx（仅支持）
* [x] GetCurrentProcessorNumber
* [x] QueryThreadCycleTime（仅支持）
* [x] GetCurrencyFormatEx
* [x] GetDateFormatEx
* [x] GetNumberFormatEx
* [x] GetTimeFormatEx
* [x] GetLocaleInfoEx
* [x] GetUserDefaultLocaleName
* [x] EnumSystemLocalesEx
* [x] GetThreadPreferredUILanguages
* [x] GetDynamicTimeZoneInformation
* [x] GetFinalPathNameByHandleW
* [x] GetFileInformationByHandleEx
* [x] SetFileInformationByHandle
* [x] GetProductInfo
* [x] GetThreadId
* [x] QueryFullProcessImageNameW
* [x] RaiseFailFastException
* [x] K32EmptyWorkingSet
* [x] K32EnumProcessModules
* [x] K32GetMappedFileNameW
* [x] K32GetModuleFileNameExW
* [x] K32GetModuleInformation
* [x] K32GetPerformanceInfo
* [x] K32GetProcessMemoryInfo
* [x] K32QueryWorkingSetEx（仅支持）
* [x] LCIDToLocaleName
* [x] LocaleNameToLCID
* [x] ResolveLocaleName
* [x] DeleteProcThreadAttributeList
* [x] InitializeProcThreadAttributeList
* [x] UpdateProcThreadAttribute（仅接口支持，实际不生效）
* [x] IsThreadAFiber
* [x] ConvertThreadToFiberEx
* [x] FlsAlloc
* [x] FlsSetValue
* [x] PowerClearRequest
* [x] PowerCreateRequest
* [x] PowerSetRequest
* [x] CloseThreadpool
* [x] CloseThreadpoolWork
* [x] CreateThreadpool
* [x] CreateThreadpoolWork
* [x] SetThreadpoolThreadMaximum
* [x] SetThreadpoolThreadMinimum
* [x] SubmitThreadpoolWork
* [x] CallbackMayRunLong
* [x] WaitForThreadpoolWorkCallbacks

**Comment by lz5921** [comment]
这个还有后续吗😂😂😂

**Comment by mingkuang-Chuyu** [comment]
> 这个还有后续吗😂😂😂

有的，还有啥需要补充吗？可以把列表给我。另外如果部分接口你这边已经有实现了，方便的话也可以提供一下。多谢。

**Comment by mingkuang-Chuyu** [comment]
> 这个还有后续吗😂😂😂

@lz5921 有的，可以随时向我联系，提供缺失的API列表。如果有部分实现也可以提供。多谢。

**Comment by jsf126** [comment]
xp系统的KERNEL32.DLL
CloseThreadpool
CreateThreadpool
SetThreadpoolThreadMaximum
SetThreadpoolThreadMinimum

可以优先支持下吗？目前编译freerdp时，最后剩下这4个不兼容的接口

**Comment by mingkuang-Chuyu** [comment]
> xp系统的KERNEL32.DLL CloseThreadpool CreateThreadpool SetThreadpoolThreadMaximum SetThreadpoolThreadMinimum
> 
> 可以优先支持下吗？目前编译freerdp时，最后剩下这4个不兼容的接口

你也可以提供PR……😉

**Comment by sonyps5201314** [comment]
> 为Chrome 110内核API缺失的情况。打勾则表明已经支持

freerdp有自己的低版本Windows API实现,你cmake时定义-DCMAKE_WINDOWS_VERSION:STRING="WINXP" 就好

**Comment by longyixiao** [comment]
chromium GetFirmwareType

GetThreadInformation

**Comment by longyixiao** [comment]
chromium 116内核暂时发现两个新函数

**Comment by longyixiao** [comment]
chromium 116内核暂时发现两个新函数
GetFirmwareType
GetThreadInformation

**Comment by mingkuang-Chuyu** [comment]
> chromium 116内核暂时发现两个新函数 GetFirmwareType GetThreadInformation
> 
> 补充 WinHttpCreateProxyResolver
> 
> WinHttpFreeProxyResult
> 
> WinHttpGetProxyForUrlEx
> 
> WinHttpGetProxyResult

@longyixiao winhttp, 完整的实现改造工作有点大，先看看又没有其他人没有啥PR吧。

**Comment by shuax** [comment]
https://github.com/google/boringssl/blob/b6e0eba6e62333652290514e51b75b966b27b27c/crypto/rand_extra/windows.c#L63

这个是不是chrome也在用

**Comment by mingkuang-Chuyu** [comment]
> https://github.com/google/boringssl/blob/b6e0eba6e62333652290514e51b75b966b27b27c/crypto/rand_extra/windows.c#L63
> 
> 这个是不是chrome也在用

Win32上用的是BCryptGenRandom，问题不大。

**Comment by mingkuang-Chuyu** [comment]
v1.0.10-Beta8已经发布，已经补充所有Windows XP RTM不支持的接口
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.10-Beta8
