### ISSUE TITLE
能与VC-LTL一起使用吗？

### ISSUE THREAD

**Issue by wangwenx190** [Chuyu-Team/YY-Thunks#3]
如题，这个项目能和VC-LTL一起使用吗？

另外再问一下，自述文件里只讲了VS的操作方法，用CMake的项目该怎么操作？

**Comment by MouriNaruto** [comment]
可以和 VC-LTL 一起使用

CMake 的话，你需要根据 CMake 配置文件语法指定引用的 lib

**Comment by wangwenx190** [comment]
我看自述文件里说的是.obj啊，怎么变成.lib了？编译为.lib也行吗？

**Comment by MouriNaruto** [comment]
.lib 相当于单个或多个 .obj 打包起来的结果

你在 lib 里用 obj 是可以的，至少 MSVC 是可以的

**Comment by wangwenx190** [comment]
好的，谢谢

**Comment by mingkuang-Chuyu** [comment]
可以一起使用。跟VC-LTl有啥关系？

但是你不能吧YY-Thunks的obj打包为 lib，否则非常容易出现搜索顺序问题。

CMake同理，在链接器附加依赖项即可。

**Comment by wangwenx190** [comment]
>
> 可以一起使用。跟VC-LTl有啥关系？
> 
没啥关系，主要是我想和VC-LTL一起用
>
> 但是你不能吧YY-Thunks的obj打包为 lib，否则非常容易出现搜索顺序问题。
> 
> CMake同理，在链接器附加依赖项即可。
>
明白了，谢谢
