### ISSUE TITLE
RtlpWakeByAddress nullptr crash running under win7

### ISSUE THREAD

**Issue by hurenhe2008** [Chuyu-Team/YY-Thunks#32]
![飞书20211104-115725](https://user-images.githubusercontent.com/10271019/140255777-c295ca59-5da9-41fc-9e2a-1eb1255b2762.png)

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.5-Beta2
请重新验证

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.6-Beta1
经过验证问题解决
