### ISSUE TITLE
补充SetThreadStackGuarantee

### ISSUE THREAD

**Issue by MisakaRay2021** [Chuyu-Team/YY-Thunks#37]
如题，能否补充一下对该函数的兼容

**Comment by mingkuang-Chuyu** [comment]
你对这个函数了解吗？如果可以，请你提供PR，我会接受

**Comment by Truuum** [comment]
This function was declared in [wine source](https://github.com/wine-mirror/wine/blob/6e32c011a2b977246f9ab2282d30b69cff90142b/dlls/kernelbase/thread.c#L575)

**Comment by Truuum** [comment]
Sent a pull request with a possible approximately correct implementation of the function.

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.7-Beta1
support now。
