### ISSUE TITLE
使用qt5.6.2编译winxp版本User32.lib相关符号解析失败

### ISSUE THREAD

**Issue by stevezhougs** [Chuyu-Team/YY-Thunks#42]
pro配置如下：
#----------------------------
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = hello
TEMPLATE = app

win32 {
    QMAKE_LFLAGS_WINDOWS = /SUBSYSTEM:WINDOWS,5.01
    QMAKE_LFLAGS_CONSOLE = /SUBSYSTEM:CONSOLE,5.01
    DEFINES += _ATL_XP_TARGETING
    QMAKE_CFLAGS += /D_USING_V120_SDK71_
    QMAKE_CXXFLAGS += /D_USING_V120_SDK71_
    LIBS *= -L"%Program Files (x86)%/Microsoft SDKs/Windows/7.1A/Lib"
    INCLUDEPATH += "%Program Files (x86)%/Microsoft SDKs/Windows/7.1A/Include"
    QMAKE_TARGET_OS = xp
    QMAKE_LIBDIR += $$PWD/objs/x86
    LIBS += YY_Thunks_for_WinXP.obj
}

SOURCES += main.cpp\
        mainwindow.cpp

HEADERS  += mainwindow.h

FORMS    += mainwindow.ui
#----------------------------
使用的是YY-Thunks-1.0.6-Binary，报错如下，

YY_Thunks_for_WinXP.obj : error LNK2019: 无法解析的外部符号 __imp__GetSystemMetrics@4，该符号在函数 _GetSystemMetricsForDpi@8 中被引用
YY_Thunks_for_WinXP.obj : error LNK2019: 无法解析的外部符号 __imp__GetDC@4，该符号在函数 "unsigned int __fastcall YY::Thunks::internal::GetDpiForSystemDownlevel(void)" (?GetDpiForSystemDownlevel@internal@Thunks@YY@@YIIXZ) 中被引用
YY_Thunks_for_WinXP.obj : error LNK2019: 无法解析的外部符号 __imp__ReleaseDC@8，该符号在函数 "unsigned int __fastcall YY::Thunks::internal::GetDpiForSystemDownlevel(void)" (?GetDpiForSystemDownlevel@internal@Thunks@YY@@YIIXZ) 中被引用
YY_Thunks_for_WinXP.obj : error LNK2019: 无法解析的外部符号 __imp__AdjustWindowRectEx@16，该符号在函数 _AdjustWindowRectExForDpi@20 中被引用
YY_Thunks_for_WinXP.obj : error LNK2019: 无法解析的外部符号 __imp__SystemParametersInfoW@16，该符号在函数 _SystemParametersInfoForDpi@20 中被引用
YY_Thunks_for_WinXP.obj : error LNK2019: 无法解析的外部符号 __imp__MonitorFromWindow@8，该符号在函数 _GetDpiForWindow@4 中被引用
release\hello.exe : fatal error LNK1120: 6 个无法解析的外部命令

**Comment by mingkuang-Chuyu** [comment]
暂时自己增加以下  User32.lib 等 引用吧

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.7-Beta2
