### ISSUE TITLE
编译最新STL，即使用YY-Thunks也会缺少CoGetApartmentType这个API函数

### ISSUE THREAD

**Issue by sonyps5201314** [Chuyu-Team/YY-Thunks#43]

**Comment by mingkuang-Chuyu** [comment]
https://github.com/microsoft/STL/blob/26a1f76a3f5a05d5815a654ca73370e4839bf441/stl/src/ppltasks.cpp
确认~

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.7-Beta2
