### ISSUE TITLE
缺少SetCoalescableTimer函数

### ISSUE THREAD

**Issue by win98se** [Chuyu-Team/YY-Thunks#45]
这个函数仅Windows 8.0和以上可用，Windows 7没有，确认安装YY-Thunks依然没解决这个问题

相关issue：https://github.com/lx-s/WinMute/issues/21

**Comment by mingkuang-Chuyu** [comment]
如果你有dwonlevel实现，可以提供

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.7-Beta2
