### ISSUE TITLE
无法定位程序输入点CancelSynchronousIo于kernel32.dll

### ISSUE THREAD

**Issue by emptyx0** [Chuyu-Team/YY-Thunks#46]
在windows server 2003上出现该提示, YY_Thunks_for_WinXP.obj已经链接进去, 该怎么解决该问题, 或者自己该怎么修改源码?

**Comment by mingkuang-Chuyu** [comment]
YY-Thunks 并没有提供 CancelSynchronousIo的实现，需要实现以下，。

可以参考Thunks目录里面的hpp文件，如果实现完成 欢迎提交 PR。

**Comment by MouriNaruto** [comment]
前段日子刚好被初雨群的群友问到这个 API 的事情，相关 NT API 看起来刚好也是和 CancelSynchronousIo 同期引进的，于是对于旧版 Windows 也许这个 API 需要变成一个返回操作失败的一个 stub。

毛利

**Comment by mingkuang-Chuyu** [comment]
@MouriNaruto 但是我并不清楚这样做是否合理。

@emptyx0 建议提供一些意见，YY-Thunks这边直接返回失败，是否可以接受？

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.8-Beta2
