### ISSUE TITLE
rust程序启动时报告 bcrypt.dll缺失

### ISSUE THREAD

**Issue by zema1** [Chuyu-Team/YY-Thunks#48]
After some struggle https://github.com/Chuyu-Team/YY-Thunks/issues/47, I was finally able to run a hello world program in windows XP, but there are still some errors before I can actually use it.

![image](https://user-images.githubusercontent.com/20637881/223035868-cafda25f-41e5-4196-9f1f-e9936eba3198.png)

Import Table Information: 
![image](https://user-images.githubusercontent.com/20637881/223036107-fdfbd78d-fd83-4b60-89fe-341d747302c2.png)

If I place a fake bcrypt.dll inside the folder, there will be other errors.

![image](https://user-images.githubusercontent.com/20637881/223036584-861e5b80-c474-499b-b77b-b0cb8f55a5df.png)
So we need to add at least these APIs.

```
// bcrypt.dll 
BCryptCloseAlgorithmProvider	
BCryptOpenAlgorithmProvider 	
BCryptGenRandom
// ntdll.dll
EtwTraceMessage        	
```

I'm almost ready to give up on xp support, there are too much trouble :(

**Comment by mingkuang-Chuyu** [comment]
EtwTraceMessage这块需要提供更多信息。看你的导入表没有导入ntdll啊？？？

**Comment by mingkuang-Chuyu** [comment]
我明白了，原来你自己搞了一份bcrypt.dll，那你怎么能吧EtwTraceMessage 列出来呢……

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.7-Beta3
已经添加了BCryptGenRandom支持，
并对BCryptCloseAlgorithmProvider, BCryptOpenAlgorithmProvider t提供了有限支持
