### ISSUE TITLE
How to generate Obj File for YY-Thunks? 

### ISSUE THREAD

**Issue by DibyaTheXPFan** [Chuyu-Team/YY-Thunks#49]
After  i compiled Visual Studio .sln File , 
It generated YY-Thunks.UnitTest.lib, YY-Thunks.UnitTest.exp,YY-Thunks.UnitTest.dll

How to get OBJ file for XP?

**Comment by DibyaTheXPFan** [comment]
'LibMaker.exe' is not recognized as an internal or external command

Can u share Libmaker.exe with source?

**Comment by mingkuang-Chuyu** [comment]
`https://github.com/Chuyu-Team/YY-Thunks/releases/download/v1.0.2.8/LibMaker.exe`

More info please see CI yml file `https://github.com/Chuyu-Team/YY-Thunks/blob/master/.github/workflows/Build%26Test.yml`

Thanks
