### ISSUE TITLE
缺少 iphlpapi 相关函数支持

### ISSUE THREAD

**Issue by zema1** [Chuyu-Team/YY-Thunks#51]
在使用 [sysinfo](https://docs.rs/sysinfo/latest/sysinfo/) 这个库时，会报错，具体的代码和测试用的 binary 见附件。
经过验证，发现缺少 `iphlpapi` 中 的如下函数：

* [x] GetIfEntry2
* [x] GetIfTable2
* [x] FreeMibTable

主要用来获取网卡信息，感谢作者~
[learn.zip](https://github.com/Chuyu-Team/YY-Thunks/files/10941117/learn.zip)

**Comment by zema1** [comment]
这三个函数在这里面都有实现，YY 可以参考下 https://github.com/wine-mirror/wine/blob/master/dlls/iphlpapi/iphlpapi_main.c
我本地仿照 YY-Thunk 的写法补充了这三个函数的定义后（没写实现），重新编译就可以运行了

**Comment by mingkuang-Chuyu** [comment]
> 这三个函数在这里面都有实现，YY 可以参考下 https://github.com/wine-mirror/wine/blob/master/dlls/iphlpapi/iphlpapi_main.c 我本地仿照 YY-Thunk 的写法补充了这三个函数的定义后（没写实现），重新编译就可以运行了

这是取网卡信息的，直接没有实现肯定是不行的。

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.7-Beta4

已经发布
