### ISSUE TITLE
Python 3.11 XP兼容（提示缺失  SetWaitableTimerEx）

### ISSUE THREAD

**Issue by felixmaker** [Chuyu-Team/YY-Thunks#55]
请求添加 SetWaitableTimerEx 实现
Python 3.11 用到了这个 SetWaitableTimerEx

**Comment by mingkuang-Chuyu** [comment]
还缺其他吗？建议完整的过一遍导入表，把需要的API都罗列一下。这样一次修完。

**Comment by felixmaker** [comment]
我看解释器就差这个 API，其他的外部依赖 openssl、tk86、libffi 我再学习一下

**Comment by felixmaker** [comment]
以我现在的认识水平来看，只缺少 SetWaitableTimerEx

**Comment by mingkuang-Chuyu** [comment]
@felixmaker ，帮忙验证一下：https://github.com/Chuyu-Team/YY-Thunks/actions/runs/4917208375

如果发现有其他API缺失则继续更新此Issue。

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.8-Beta1

**Comment by Z-fly** [comment]
我想问下 Python3.11如何运行在xp上?
