### ISSUE TITLE
请问这个可以用在QT项目上么？

### ISSUE THREAD

**Issue by Mr-ShiHuaYu** [Chuyu-Team/YY-Thunks#59]
因为QT高版本不支持windows的低版本，比如，QT6不支持windows7，QT5.7以上不支持xp，如果使用msvc编译器的话，应该问题不大，但如果使用的是mingw编译器的话，不知道可以么？

**Comment by mingkuang-Chuyu** [comment]
没有特意适配过mingw，不过应该问题不大。
