### ISSUE TITLE
Tokio support (Rust)

### ISSUE THREAD

**Issue by BlueGradientHorizon** [Chuyu-Team/YY-Thunks#60]
Hello.
`Tokio is an event-driven, non-blocking I/O platform for writing asynchronous applications with the Rust programming language.`

I'm currently writing a small server-client application using the Tokio crate. I intended to write a very simple client with minimal dependencies, but it turns out that the core of my program - Tokio - already includes a few unresolved characters on Windows XP.
When I try to run the given program's executable on Win XP:

Cargo.toml:
```rust
[package]
...

[dependencies]
tokio = { version = "1", features = ["full"] }
```
src/main.rs:
```rust
#[tokio::main]
async fn main() { }
```
i get two unresolved characters - GetQueuedCompletionStatusEx ([MS docs](https://learn.microsoft.com/en-us/windows/win32/fileio/getqueuedcompletionstatusex-func)) in kernel32.dll and NtCancelIoFileEx ([MS docs](https://learn.microsoft.com/en-us/windows/win32/devnotes/nt-cancel-io-file-ex)) in ntdll.dll.

And this program (an example of a simple TCP server from https://crates.io/crates/tokio):
```rust
use tokio::net::TcpListener;
use tokio::io::{AsyncReadExt, AsyncWriteExt};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
     let listener = TcpListener::bind("127.0.0.1:8080").await?;

     loop {
         let (mut socket, _) = listener.accept().await?;

         tokio::spawn(async move {
             let mutbuf = [0; 1024];

             // In a loop, read data from the socket and write the data back.
             loop {
                 let n = match socket.read(&mut buf).await {
                     // socket closed
                     Ok(n) if n == 0 => return,
                     Ok(n) => n,
                     Err(e) => {
                         eprintln!("failed to read from socket; err = {:?}", e);
                         return;
                     }
                 };

                 // Write the data back
                 if let Err(e) = socket.write_all(&buf[0..n]).await {
                     eprintln!("failed to write to socket; err = {:?}", e);
                     return;
                 }
             }
         });
     }
}
```
adds one more unresolved symbol - SetFileCompletionNotificationModes ([MS docs](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setfilecompletionnotificationmodes)) in kernel32.dll

Is it possible to implement these functions?

Wine implementation of these functions:

- [GetQueuedCompletionStatusEx](https://github.com/wine-mirror/wine/blob/cb33d402bb7fc44a51cd96adfbe740d4b2d7a134/dlls/kernelbase/sync.c#L1143)
- [NtCancelIoFileEx](https://github.com/wine-mirror/wine/blob/cb33d402bb7fc44a51cd96adfbe740d4b2d7a134/dlls/ntdll/unix/file.c#L6231)
- [SetFileCompletionNotificationModes](https://github.com/wine-mirror/wine/blob/cb33d402bb7fc44a51cd96adfbe740d4b2d7a134/dlls/kernel32/file.c#L256)

I appreciate your work. Thanks.

**Comment by mingkuang-Chuyu** [comment]
I'm sorry. I don't know... SetFileCompletionNotificationModes.

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.9-Beta3

done!

**Comment by zhuxiujia** [comment]
> https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.9-Beta3
> 
> done!

i try this code(tokio) on  windows server 2008( win vista) fail (PermissionDenied)

![1708449346053](https://github.com/Chuyu-Team/YY-Thunks/assets/3481148/e98b07de-1271-4237-ae9e-97af374875b3)
