### ISSUE TITLE
缺少GetQueuedCompletionStatusEx 函数

### ISSUE THREAD

**Issue by sinfee** [Chuyu-Team/YY-Thunks#63]
非常感谢开发这个项目！

在winxp / 2003等系统的32位或64位上运行时提示：
无法定义程序输入点 GetQueuedCompletionStatusEx 于动态链接库 KERNEL32.dll 上
麻烦帮解决一下

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/issues/60

GetQueuedCompletionStatusEx接口建议已经在上面这个issue中，现在开始关闭这个链接，我们统一在60这边跟踪进度。

**Comment by mingkuang-Chuyu** [comment]
以及发布完成，下载该版本即可：
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.9-Beta3
