### ISSUE TITLE
Windows XP运行slint提示找不到IsProcessDPIAware

### ISSUE THREAD

**Issue by jiangyubao** [Chuyu-Team/YY-Thunks#64]
经过沟通，发现slint依赖里缺少如下函数：

## USER32.DLL
* [x] IsProcessDPIAware
* [x] SetWindowDisplayAffinity
* [x] GetTouchInputInfo
* [x] RegisterTouchWindow
* [x] CloseTouchInputHandle

## DWMAPI.DLL
* [x] DwmEnableBlurBehindWindow

**Comment by mingkuang-Chuyu** [comment]
接口以及全部提交，CI构建完成后，请帮忙使用产物进行验证。

https://github.com/Chuyu-Team/YY-Thunks/actions/runs/6407347125

**Comment by mingkuang-Chuyu** [comment]
验证通过并且已经发布
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.9-Beta4
