### ISSUE TITLE
可否补充几个常见DWM接口

### ISSUE THREAD

**Issue by wangwenx190** [Chuyu-Team/YY-Thunks#65]
- [x] [DwmIsCompositionEnabled](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmiscompositionenabled)
    - *fEnabled = FALSE, 返回 S_OK
- [x] [DwmEnableComposition](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmenablecomposition)
    - 尝试开启时返回错误。但是应该返回什么错误代码呢？
- [x] [DwmExtendFrameIntoClientArea](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmextendframeintoclientarea)
    - 返回 DWM_E_COMPOSITIONDISABLED
- [x] [DwmDefWindowProc](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmdefwindowproc)
    -  可以调用 DefWindowProc ？？？？
    - 根据我的经验，如果该函数返回FALSE，则调用方会自行调用DefWindowProc。所以我的意见是，不支持的情况下直接返回FALSE。
- [x] [DwmGetColorizationColor](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmgetcolorizationcolor)
    -  返回 DWM_E_COMPOSITIONDISABLED ？？
    - 我感觉无所谓吧，大多数代码都不会检查这个函数的返回值，我觉得可以返回一个固定的颜色，然后返回S_OK
- [x] [DwmGetWindowAttribute](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmgetwindowattribute)
   -   返回 DWM_E_COMPOSITIONDISABLED ？？
   -  返回这个应该没问题
- [x] [DwmSetWindowAttribute](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute)
   -    返回 DWM_E_COMPOSITIONDISABLED ？？
   -  同上
- [x] [DwmFlush](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmflush)
   - 直接返回  S_OK。

我个人认为这些函数在不存在时都可以直接返回`S_OK`（或者`E_FAIL`），因为根据我的经验，这些函数失败后一般不会导致程序的行为有明显改变。

**Comment by MouriNaruto** [comment]
要确认模拟 S_OK 还是 E_FAIL 可能需要额外引入模拟的目标平台等级吧

譬如如果只需要模拟 Vista 或者 7 的行为，那就是 E_FAIL 和 FALSE 是没啥问题的
但是有些家伙最低系统要求是 Windows 8 起步，那可能一些内容需要返回 S_OK 和 TRUE 才能让其正常执行逻辑

毛利

**Comment by mingkuang-Chuyu** [comment]
我感觉补充没有问题，但是先把需要补充的函数列出来，以及回退行为是什么？我们需要在先讨论，最好可以给我经验意见。

仅仅通过我一个人的直觉补充那么多我不擅长的API，感觉容易出错。

**Comment by mingkuang-Chuyu** [comment]
已经采纳意见。
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.10-Beta2
