### ISSUE TITLE
MFC默认项目添加鸭船obj，编译后无法在XP上运行

### ISSUE THREAD

**Issue by oper1000** [Chuyu-Team/YY-Thunks#67]
使用 VS2022 或者 VS2019 在Windows 11 上 新建一个默认的对话框MFC项目。

连接器添加 xp 的obj，然后编译，在Win11上正常运行DEMO。

然后把编译好的 Release 放到 XP 的虚拟机  

运行报错。

我打开方式错了？

![D_OQ(NF%_6L_BDAXC2QMDQT](https://github.com/Chuyu-Team/YY-Thunks/assets/993995/d1b07aee-a401-468e-8b5a-a89eb1f6e689)

![image](https://github.com/Chuyu-Team/YY-Thunks/assets/993995/1faa02ad-c436-4e15-9a0e-58faa5821c60)

**Comment by xenoplastic** [comment]
很明显YY-Thunks和最终exe能否在XP上运行没关系：YY-Thunks只是实现了部分在XP上没有的函数，最终生成的程序能否在XP上运行取决于你的编译器是否支持生成兼容XP的程序。

**Comment by felixmaker** [comment]
> > 很明显YY-Thunks和最终exe能否在XP上运行没关系：YY-Thunks只是实现了部分在XP上没有的函数，最终生成的程序能否在XP上运行取决于你的编译器是否支持生成兼容XP的程序。
> 
> 也就是说，还是得用 v141_xp 平台工具集去生成，而不能用最新的 v143？

还得再用 VC-LTL5

**Comment by mingkuang-Chuyu** [comment]
@oper1000 我先说明，上面这些人说的不对，这是是修改所需最低版本不对的关系。

请使用NuGet般YY-Thunks，或者自己在链接器 - 系统 修改所需最低版本 5.1
