### ISSUE TITLE
是否能支持golang

### ISSUE THREAD

**Issue by heheda123123** [Chuyu-Team/YY-Thunks#69]
golang新版本已经放弃了对xp和win7的支持，通过yy-thunks是否能让新版本golang仍然支持winxp和win7?

**Comment by yangjuncode** [comment]
链接过程不太一样，原理倒是行得通的，不过应该要patch go源码才行了，xp希望不大，win7应该还是可以的

**Comment by mingkuang-Chuyu** [comment]
建议你试试，主要是我并不清楚需要修改什么……

**Comment by zhuxiujia** [comment]
> golang新版本已经放弃了对xp和win7的支持，通过yy-thunks是否能让新版本golang仍然支持winxp和win7?

经过测试，go编译器降低到1.13还是哪个版本可以支持xp和win7，因为go的语法都是向下兼容。你代码修改量并不大，建议不要用例如 any改为interface{}  可以完美支持xp

**Comment by yangjuncode** [comment]
> 建议你试试，主要是我并不清楚需要修改什么……

golang 新版本会用一些新的api, 当然是旧版本系统没有的。如：
https://github.com/golang/go/blob/2e064cf14441460290fd25d9d61f02a9d0bae671/src/runtime/os_windows.go#L250C2-L254C77

```
        bcryptPrimitives := windowsLoadSystemLib(bcryptprimitivesdll[:])
        if bcryptPrimitives == 0 {
                throw("bcryptprimitives.dll not found")
        }
        _ProcessPrng = windowsFindfunc(bcryptPrimitives, []byte("ProcessPrng\000"))
```

**Comment by mingkuang-Chuyu** [comment]
请直接提供使用yY-Thunks后旧系统任然缺失的API。
或者提供构建产物，这样我可以直接获取API导入关系。

现在这样简单的扩列一些局部代码对问题其实没有太大帮助

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yangjuncode** [comment]
在go上应该是应用不了yy-thunks,毕竟go无法用vc, 也没有 c/c++那样的链接过程。
只是原理相通，可以模仿处理，但处理方法需要根据go来特殊处理，目前我能想到的是需要patch golang src才行

**Comment by mingkuang-Chuyu** [comment]
@yangjuncode 那很抱歉，只能作为无效反馈关闭了。因为YY-Thunks是借助于链接时Hook，而go的情况看YY-Thunks的原理差异较大，不是顺手可以完成的事情。

本人对go也没有什么兴趣，暂时也不会特意去支持go。
