### ISSUE TITLE
为rust 1.78提供Windows XP RTM/Windows 7 RTM兼容

### ISSUE THREAD

**Issue by zhuxiujia** [Chuyu-Team/YY-Thunks#76]
yy-thunks version: v1.0.9 beta3

# 问题情况
* [x] ProcessPrng（Windows Vista RTM缺失）
* [x] rust raw-dylib引用规则适配（#78）

# 复现代码(#60) 
```rust
use tokio::net::TcpListener;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let listener = TcpListener::bind("127.0.0.1:8080").await?;// 这里报错PermissionDined
    loop {
        let (mut socket, _) = listener.accept().await?;
        tokio::spawn(async move {
            let mut buf = [0; 1024];
            loop {
                let n = match socket.read(&mut buf).await {
                    // socket closed
                    Ok(n) if n == 0 => return,
                    Ok(n) => n,
                    Err(e) => {
                        eprintln!("failed to read from socket; err = {:?}", e);
                        return;
                    }
                };
                if let Err(e) = socket.write_all(&buf[0..n]).await {
                    eprintln!("failed to write to socket; err = {:?}", e);
                    return;
                }
            }
        });
    }
}
```

* 首先vstudio 2017  https://visualstudio.microsoft.com/zh-hans/vs/older-downloads/ ,安装的时候要勾选windows_xp_build 选项
* 安装rust编译器 https://www.rust-lang.org/
* 按照readme的步骤，安装thunk编译工具, 地址是 https://github.com/felixmaker/thunk
* 切换工具链指令
```
rustup default  nightly
```
* 更新到最新的每夜版
```
rustup update
```
* 执行上面的编译tokio代码
```
thunk --os xp --arch x86 -- --release
```

* 拷贝`target/winxp_build/i686-pc-windows-msvc/release/xxxx.exe到winserver 2008/vista`虚拟机

![1712301054315](https://github.com/Chuyu-Team/YY-Thunks/assets/3481148/43d89c37-e8b9-464e-bc3f-674ed264cc36)

**Comment by mingkuang-Chuyu** [comment]
@zhuxiujia 直接提供编译产物即可，从编译产物中可以直接看到依赖了那些API。

**Comment by zhuxiujia** [comment]
以下是编译产物
[w.zip](https://github.com/Chuyu-Team/YY-Thunks/files/14884013/w.zip)

**Comment by mingkuang-Chuyu** [comment]
新版本已经发布
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.10-Beta2

**Comment by mingkuang-Chuyu** [comment]
ProcessPrng版本判断错误，Vista也不存在此接口。

**Comment by muyu1944** [comment]
@mingkuang-Chuyu 从 #78 过来，beta4在xp x86下依然会出现这个函数
