### ISSUE TITLE
Qt Windows Extras依赖 `DwmInvalidateIconicBitmaps`, `DwmSetIconicLivePreviewBitmap`等API

### ISSUE THREAD

**Issue by lygstate** [Chuyu-Team/YY-Thunks#87]
参考链接 https://bugreports.qt.io/browse/QTBUG-63627?focusedCommentId=373795&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.1.1-Beta1
新版本已经发布
