### ISSUE TITLE
Windows XP RTM 没有 DecodePointer EncodePointer

### ISSUE THREAD

**Issue by lygstate** [Chuyu-Team/YY-Thunks#89]
参考链接

https://stackoverflow.com/questions/2484511/can-i-use-visual-studio-2010s-c-compiler-with-visual-studio-2008s-c-runtim

**Comment by mingkuang-Chuyu** [comment]
这是一直以来就有的实现。反馈时可以先搜索一下代码……

https://github.com/Chuyu-Team/YY-Thunks/blob/c418ce83a5690495a60bdcaa61704d5f8112aa10/src/Thunks/api-ms-win-core-util.hpp#L16

**Comment by lygstate** [comment]
不是通过代码发现的
是通过 https://github.com/Chuyu-Team/YY-Thunks/releases/download/v1.0.10-Beta8/YY-Thunks-1.0.10-Beta8-Binary.zip
发现的

@mingkuang-Chuyu 

那估计是发布版本的问题了

**Comment by mingkuang-Chuyu** [comment]
产物也没有问题。x86的Win2K/WinXP obj文件均存在DecodePointer EncodePointer

如果你说有问题，麻烦请提供详细信息……

谢谢
________________________________
发件人: Yonggang Luo ***@***.***>
发送时间: 2024年5月29日 10:41
收件人: Chuyu-Team/YY-Thunks ***@***.***>
抄送: mingkuang ***@***.***>; Mention ***@***.***>
主题: Re: [Chuyu-Team/YY-Thunks] Windows XP RTM 没有 DecodePointer EncodePointer (Issue #89)


不是通过代码发现的
是通过 https://github.com/Chuyu-Team/YY-Thunks/releases/download/v1.0.10-Beta8/YY-Thunks-1.0.10-Beta8-Binary.zip
发现的

@mingkuang-Chuyu<https://github.com/mingkuang-Chuyu>

那估计是发布版本的问题了

―
