### ISSUE TITLE
need the below APIs on Windows xp

### ISSUE THREAD

**Issue by znsoftm** [Chuyu-Team/YY-Thunks#9]
EventRegister 
EventUnregister 
EventWrite 
EventWriteTransfer 
EventWriteEx 
EventSetInformation

**Comment by znsoftm** [comment]
in advapi32.dll

**Comment by znsoftm** [comment]
They are original in  advapi32.dll

**Comment by mingkuang-Chuyu** [comment]
Hi~~  Can you provide the code?

**Comment by mingkuang-Chuyu** [comment]
长时间未答复。关闭。
